##================ Users APIs
### get users
GET http://localhost:8001/api/v1/users

### Get single user
GET http://localhost:8001/api/v1/users/64ba0ee4c3251953d0d4cafb

###post new  user
POST http://localhost:8001/api/v1/users
Content-Type: application/json

{
    "firstName":"Pradeep",
    "lastName":"Dhital",
    "email":"pradeepdhitall@gmail.com",
    "phone":"0451644397",
    "dob":"03/09/1999",
    "address":{
         "street": "101/1-3 Clarence Street",
         "suburb":"Strathfield",
         "state": "NSW",
        "postCode": "2135"
    },
    "password":"Pradeep"
}

##============   Categories APIs

### Get All categories
GET http://localhost:8001/api/v1/categories


### Get single category
GET http://localhost:8001/api/v1/categories/64a28cebc7077fa71eec5a8c


##============ Products APIs

### Get All Products
GET http://localhost:8001/api/v1/products

### Get Single Product
GET http://localhost:8001/api/v1/products/64a28da7c7077fa71eec6166

### Get products relevent to specific categories
GET http://localhost:8001/api/v1/products/categoriesfilter/64a28cebc7077fa71eec5a8c

##============ Items APIs

### Get All Items
GET http://localhost:8001/api/v1/items

### Get Single Item
GET http://localhost:8001/api/v1/items/64a9544bd9c3ea1d09a8e4b2



### post items

Post http://localhost:8001/api/v1/items/


### post items

Get http://localhost:8001/api/v1/cart/

### payment router
POST http://localhost:8001/api/v1/payment/
Content-Type: application/json

{
  "products": [
    {
      "_id": "64dadc95978e25b7b5ce9d2b",
      "status": "active",
      "name": "Harmony Hues Bed Sheet",
      "sku": "Harmony Hues Bed Sheet",
      "slug": "harmony-hues-bed-sheet",
      "description": "The Harmony Hues Bed Sheet showcases a gradient of calming colors that seamlessly blend together. It creates a sense of harmony and balance, transforming your bed into a peaceful oasis for relaxation.",
      "catId": "64dac105487491a46c1b322b",
      "subCatId": "64dac18b487491a46c1b327f",
      "productId": "64dac1f3487491a46c1b3712",
      "quantity": 33,
      "images": [],
      "thumbnail": "https://res.cloudinary.com/dt5eiyxyc/image/upload/v1692064905/pgjwngpxz41bzge4qtvv.jpg",
      "price": 32,
      "salesPrice": 0,
      "salesStartDate": null,
      "salesEndDate": null,
      "rating": 5,
      "filterName": "Size",
      "filters": [],
      "createdAt": "2023-08-15T02:01:57.054Z",
      "updatedAt": "2023-08-15T02:01:57.054Z",
      "__v": 0,
      "count": 5,
      "filter": "Single"
    },
    {
      "_id": "64dadd74478e25b7b5ce9d4a",
      "status": "active",
      "name": "Rainforest Retreat Bed Sheet",
      "sku": "Rainforest Retreat Bed Sheet",
      "slug": "rainforest-retreat-bed-sheet",
      "description": "Escape to the heart of a tropical rainforest with the Rainforest Retreat Bed Sheet. The vibrant greens and vivid flora transport you to a lush oasis, making bedtime a journey into a world of natural wonder.",
      "catId": "64dac105487491a46c1b322b",
      "subCatId": "64dac18b487491a46c1b327f",
      "productId": "64dac1f3487491a46c1b3712",
      "quantity": 33,
      "images": [],
      "thumbnail": "https://res.cloudinary.com/dt5eiyxyc/image/upload/v1692065136/vqotsrpkeisfdndkajmm.jpg",
      "price": 35,
      "salesPrice": 0,
      "salesStartDate": null,
      "salesEndDate": null,
      "rating": 5,
      "filterName": "Size",
      "filters": [],
      "createdAt": "2023-08-15T02:05:40.223Z",
      "updatedAt": "2023-08-15T02:05:40.223Z",
      "__v": 0,
      "count": 4,
      "filter": "Single"
    },
    {
      "_id": "64dadb73478e25b7b5ce9d10",
      "status": "active",
      "name": "Whispering Willows Bed Sheet",
      "sku": "Whispering Willows Bed Sheet",
      "slug": "whispering-willows-bed-sheet",
      "description": "The Whispering Willows Bed Sheet is adorned with intricate patterns of graceful willow branches, creating a soothing atmosphere reminiscent of a tranquil forest. Its soft colors and gentle textures offer a sense of calm to your bedroom.",
      "catId": "64dac105487491a46c1b322b",
      "subCatId": "64dac18b487491a46c1b327f",
      "productId": "64dac1f3487491a46c1b3712",
      "quantity": 33,
      "images": [],
      "thumbnail": "https://res.cloudinary.com/dt5eiyxyc/image/upload/v1692064617/ptfx2yyf0cvmmejvsb0w.jpg",
      "price": 45,
      "salesPrice": 0,
      "salesStartDate": null,
      "salesEndDate": null,
      "rating": 5,
      "filterName": "Color",
      "filters": [],
      "createdAt": "2023-08-15T01:57:07.610Z",
      "updatedAt": "2023-08-15T01:57:07.610Z",
      "__v": 0,
      "count": 1,
      "filter": ""
    },
    {
      "_id": "64dadbf0478e25b7b5ce9d1c",
      "status": "active",
      "name": "Galactic Glow Bed Sheet",
      "sku": "Galactic Glow Bed Sheet",
      "slug": "galactic-glow-bed-sheet",
      "description": "Transport your dreams to the cosmos with the Galactic Glow Bed Sheet. Its deep blue background is speckled with shimmering stars that glow in the dark, making bedtime an adventure to the far reaches of space.",
      "catId": "64dac105487491a46c1b322b",
      "subCatId": "64dac18b487491a46c1b327f",
      "productId": "64dac1f3487491a46c1b3712",
      "quantity": 63,
      "images": [],
      "thumbnail": "https://res.cloudinary.com/dt5eiyxyc/image/upload/v1692064745/bzxqfipb2wjbwvnm9ioy.jpg",
      "price": 40,
      "salesPrice": 0,
      "salesStartDate": null,
      "salesEndDate": null,
      "rating": 5,
      "filterName": "Size",
      "filters": [],
      "createdAt": "2023-08-15T01:59:12.886Z",
      "updatedAt": "2023-08-15T01:59:12.886Z",
      "__v": 0,
      "count": 10,
      "filter": ""
    }
  ],
  "deliveryCharge": 48,
  "gstRate": 0.1
}

