##==========Categories APIs

### Get All categories
GET http://localhost:8001/api/v1/categories


### Get single category
GET http://localhost:8001/api/v1/categories/64a28cebc7077fa71eec5a8c


##============ Products APIs

### Get All Products
GET http://localhost:8001/api/v1/products

### Get Single Product
GET http://localhost:8001/api/v1/products/64a28da7c7077fa71eec6166

### Get products relevent to specific categories
GET http://localhost:8001/api/v1/products/categoriesfilter/64a28cebc7077fa71eec5a8c

##============ Items APIs

### Get All Items
GET http://localhost:8001/api/v1/items

### Get Single Item
GET http://localhost:8001/api/v1/items/64a9544bd9c3ea1d09a8e4b2
### Get  Items by products
GET http://localhost:8001/api/v1/items/productfilter/64a28df5c7077fa71eec617f